Repository uhafner/coverage-model, pull requests merged in 2023-01, with the labels that each got.

#52 Add tests for `FractionValue`
  src/main/java/edu/hm/hafner/metric/FractionValue.java
  src/test/java/edu/hm/hafner/metric/FractionValueTest.java
Labels: tests

#53 Refactor model so that PIT results also produce line coverages
  src/main/java/edu/hm/hafner/metric/FractionValue.java
  src/test/java/edu/hm/hafner/metric/FractionValueTest.java
Labels: enhancement

#59 Rewrite PIT parser: now line and mutation coverage is extracted
  src/main/java/edu/hm/hafner/metric/ClassNode.java
  src/main/java/edu/hm/hafner/metric/Coverage.java
  src/main/java/edu/hm/hafner/metric/FileNode.java
  src/main/java/edu/hm/hafner/metric/Mutation.java
  src/main/java/edu/hm/hafner/metric/MutationStatus.java
  src/main/java/edu/hm/hafner/metric/MutationValue.java
  src/main/java/edu/hm/hafner/metric/Mutator.java
  src/main/java/edu/hm/hafner/metric/Node.java
  src/main/java/edu/hm/hafner/metric/Value.java
  src/main/java/edu/hm/hafner/metric/parser/CoverageParser.java
  src/main/java/edu/hm/hafner/metric/parser/PitestParser.java
  src/main/java/edu/hm/hafner/metric/parser/XmlParser.java
  src/test/java/edu/hm/hafner/metric/ClassNodeTest.java
  src/test/java/edu/hm/hafner/metric/MutationTest.java
  src/test/java/edu/hm/hafner/metric/MutationValueTest.java
  src/test/java/edu/hm/hafner/metric/parser/AbstractParserTest.java
  src/test/java/edu/hm/hafner/metric/parser/PitestParserTest.java
Labels: feature

#63 Rewrite Cobertura parser
  README.md
  src/main/java/edu/hm/hafner/metric/Node.java
  src/main/java/edu/hm/hafner/metric/parser/CoberturaParser.java
  src/test/java/edu/hm/hafner/metric/parser/CoberturaParserTest.java
  src/test/resources/cobertura-lots-of-data.xml
  src/test/resources/cobertura-python.xml
Labels: enhancement
